# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sports_lottery_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 455)
        Dialog.setMaximumSize(QtCore.QSize(922, 16777215))
        Dialog.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/p2.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 350))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grpNumbers = QtWidgets.QGroupBox(self.frame_2)
        self.grpNumbers.setMaximumSize(QtCore.QSize(400, 400))
        self.grpNumbers.setObjectName("grpNumbers")
        self.grpNumbersLayout = QtWidgets.QGridLayout(self.grpNumbers)
        self.grpNumbersLayout.setObjectName("grpNumbersLayout")
        self.label_3 = QtWidgets.QLabel(self.grpNumbers)
        self.label_3.setMinimumSize(QtCore.QSize(10, 0))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.grpNumbersLayout.addWidget(self.label_3, 1, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.grpNumbers)
        self.label_2.setMinimumSize(QtCore.QSize(10, 0))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.grpNumbersLayout.addWidget(self.label_2, 0, 6, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton.setText("")
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.grpNumbersLayout.addWidget(self.pushButton, 0, 7, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_2.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_2.setText("")
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.grpNumbersLayout.addWidget(self.pushButton_2, 0, 5, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_3.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_3.setText("")
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.grpNumbersLayout.addWidget(self.pushButton_3, 0, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_4.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_4.setText("")
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.grpNumbersLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_5.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_5.setText("")
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.grpNumbersLayout.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_6.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_6.setText("")
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.grpNumbersLayout.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_7.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_7.setText("")
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.grpNumbersLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_8.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_8.setText("")
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.grpNumbersLayout.addWidget(self.pushButton_8, 1, 7, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_9.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_9.setText("")
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.grpNumbersLayout.addWidget(self.pushButton_9, 2, 7, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_10.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_10.setText("")
        self.pushButton_10.setDefault(False)
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.grpNumbersLayout.addWidget(self.pushButton_10, 3, 7, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_11.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_11.setText("")
        self.pushButton_11.setDefault(False)
        self.pushButton_11.setFlat(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.grpNumbersLayout.addWidget(self.pushButton_11, 4, 7, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_12.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_12.setText("")
        self.pushButton_12.setDefault(False)
        self.pushButton_12.setFlat(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.grpNumbersLayout.addWidget(self.pushButton_12, 1, 5, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_13.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_13.setText("")
        self.pushButton_13.setDefault(False)
        self.pushButton_13.setFlat(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.grpNumbersLayout.addWidget(self.pushButton_13, 1, 4, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_14.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_14.setText("")
        self.pushButton_14.setDefault(False)
        self.pushButton_14.setFlat(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.grpNumbersLayout.addWidget(self.pushButton_14, 1, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_15.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_15.setText("")
        self.pushButton_15.setDefault(False)
        self.pushButton_15.setFlat(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.grpNumbersLayout.addWidget(self.pushButton_15, 1, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_16.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_16.setText("")
        self.pushButton_16.setDefault(False)
        self.pushButton_16.setFlat(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.grpNumbersLayout.addWidget(self.pushButton_16, 1, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_17.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_17.setText("")
        self.pushButton_17.setDefault(False)
        self.pushButton_17.setFlat(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.grpNumbersLayout.addWidget(self.pushButton_17, 1, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_18.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_18.setText("")
        self.pushButton_18.setDefault(False)
        self.pushButton_18.setFlat(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.grpNumbersLayout.addWidget(self.pushButton_18, 2, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_19.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_19.setText("")
        self.pushButton_19.setDefault(False)
        self.pushButton_19.setFlat(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.grpNumbersLayout.addWidget(self.pushButton_19, 2, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_20.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_20.setText("")
        self.pushButton_20.setDefault(False)
        self.pushButton_20.setFlat(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.grpNumbersLayout.addWidget(self.pushButton_20, 2, 2, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_21.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_21.setText("")
        self.pushButton_21.setDefault(False)
        self.pushButton_21.setFlat(False)
        self.pushButton_21.setObjectName("pushButton_21")
        self.grpNumbersLayout.addWidget(self.pushButton_21, 2, 3, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_22.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_22.setText("")
        self.pushButton_22.setDefault(False)
        self.pushButton_22.setFlat(False)
        self.pushButton_22.setObjectName("pushButton_22")
        self.grpNumbersLayout.addWidget(self.pushButton_22, 2, 4, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_23.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_23.setText("")
        self.pushButton_23.setDefault(False)
        self.pushButton_23.setFlat(False)
        self.pushButton_23.setObjectName("pushButton_23")
        self.grpNumbersLayout.addWidget(self.pushButton_23, 2, 5, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_24.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_24.setText("")
        self.pushButton_24.setDefault(False)
        self.pushButton_24.setFlat(False)
        self.pushButton_24.setObjectName("pushButton_24")
        self.grpNumbersLayout.addWidget(self.pushButton_24, 3, 5, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_25.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_25.setText("")
        self.pushButton_25.setDefault(False)
        self.pushButton_25.setFlat(False)
        self.pushButton_25.setObjectName("pushButton_25")
        self.grpNumbersLayout.addWidget(self.pushButton_25, 4, 5, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_26.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_26.setText("")
        self.pushButton_26.setDefault(False)
        self.pushButton_26.setFlat(False)
        self.pushButton_26.setObjectName("pushButton_26")
        self.grpNumbersLayout.addWidget(self.pushButton_26, 4, 4, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_27.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_27.setText("")
        self.pushButton_27.setDefault(False)
        self.pushButton_27.setFlat(False)
        self.pushButton_27.setObjectName("pushButton_27")
        self.grpNumbersLayout.addWidget(self.pushButton_27, 3, 4, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_28.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_28.setText("")
        self.pushButton_28.setDefault(False)
        self.pushButton_28.setFlat(False)
        self.pushButton_28.setObjectName("pushButton_28")
        self.grpNumbersLayout.addWidget(self.pushButton_28, 3, 3, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_29.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_29.setText("")
        self.pushButton_29.setDefault(False)
        self.pushButton_29.setFlat(False)
        self.pushButton_29.setObjectName("pushButton_29")
        self.grpNumbersLayout.addWidget(self.pushButton_29, 4, 3, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_30.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_30.setText("")
        self.pushButton_30.setDefault(False)
        self.pushButton_30.setFlat(False)
        self.pushButton_30.setObjectName("pushButton_30")
        self.grpNumbersLayout.addWidget(self.pushButton_30, 4, 2, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_31.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_31.setText("")
        self.pushButton_31.setDefault(False)
        self.pushButton_31.setFlat(False)
        self.pushButton_31.setObjectName("pushButton_31")
        self.grpNumbersLayout.addWidget(self.pushButton_31, 3, 2, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_32.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_32.setText("")
        self.pushButton_32.setDefault(False)
        self.pushButton_32.setFlat(False)
        self.pushButton_32.setObjectName("pushButton_32")
        self.grpNumbersLayout.addWidget(self.pushButton_32, 3, 1, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_33.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_33.setText("")
        self.pushButton_33.setDefault(False)
        self.pushButton_33.setFlat(False)
        self.pushButton_33.setObjectName("pushButton_33")
        self.grpNumbersLayout.addWidget(self.pushButton_33, 4, 1, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_34.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_34.setText("")
        self.pushButton_34.setDefault(False)
        self.pushButton_34.setFlat(False)
        self.pushButton_34.setObjectName("pushButton_34")
        self.grpNumbersLayout.addWidget(self.pushButton_34, 4, 0, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.grpNumbers)
        self.pushButton_35.setMinimumSize(QtCore.QSize(45, 45))
        self.pushButton_35.setText("")
        self.pushButton_35.setDefault(False)
        self.pushButton_35.setFlat(False)
        self.pushButton_35.setObjectName("pushButton_35")
        self.grpNumbersLayout.addWidget(self.pushButton_35, 3, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.grpNumbers)
        self.grpBets = QtWidgets.QGroupBox(self.frame_2)
        self.grpBets.setMaximumSize(QtCore.QSize(16777215, 400))
        self.grpBets.setObjectName("grpBets")
        self.grpBetsLayout = QtWidgets.QVBoxLayout(self.grpBets)
        self.grpBetsLayout.setObjectName("grpBetsLayout")
        self.rdBets_1 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_1.setObjectName("rdBets_1")
        self.grpBetsLayout.addWidget(self.rdBets_1)
        self.rdBets_2 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_2.setObjectName("rdBets_2")
        self.grpBetsLayout.addWidget(self.rdBets_2)
        self.rdBets_3 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_3.setObjectName("rdBets_3")
        self.grpBetsLayout.addWidget(self.rdBets_3)
        self.rdBets_4 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_4.setObjectName("rdBets_4")
        self.grpBetsLayout.addWidget(self.rdBets_4)
        self.rdBets_5 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_5.setObjectName("rdBets_5")
        self.grpBetsLayout.addWidget(self.rdBets_5)
        self.horizontalLayout_2.addWidget(self.grpBets)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnStart = QtWidgets.QPushButton(self.frame_3)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_3.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(self.frame_3)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_3.addWidget(self.btnStop)
        self.btnAutoGenerate = QtWidgets.QPushButton(self.frame_3)
        self.btnAutoGenerate.setObjectName("btnAutoGenerate")
        self.horizontalLayout_3.addWidget(self.btnAutoGenerate)
        self.btnReturn = QtWidgets.QPushButton(self.frame_3)
        self.btnReturn.setObjectName("btnReturn")
        self.horizontalLayout_3.addWidget(self.btnReturn)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        self.btnReturn.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "传统型体育彩票"))
        self.grpNumbers.setTitle(_translate("Dialog", "幸运号码"))
        self.grpBets.setTitle(_translate("Dialog", "请投注"))
        self.rdBets_1.setText(_translate("Dialog", "第一注"))
        self.rdBets_2.setText(_translate("Dialog", "第二注"))
        self.rdBets_3.setText(_translate("Dialog", "第三注"))
        self.rdBets_4.setText(_translate("Dialog", "第四注"))
        self.rdBets_5.setText(_translate("Dialog", "第五注"))
        self.btnStart.setText(_translate("Dialog", "开始"))
        self.btnStop.setText(_translate("Dialog", "停止"))
        self.btnAutoGenerate.setText(_translate("Dialog", "自动"))
        self.btnReturn.setText(_translate("Dialog", "返回"))

