# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sports_lottery_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 455)
        Dialog.setMaximumSize(QtCore.QSize(922, 16777215))
        Dialog.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/p2.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 350))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grpNumbers = QtWidgets.QGroupBox(self.frame_2)
        self.grpNumbers.setMaximumSize(QtCore.QSize(400, 400))
        self.grpNumbers.setObjectName("grpNumbers")
        self.grpNumbersLayout = QtWidgets.QGridLayout(self.grpNumbers)
        self.grpNumbersLayout.setObjectName("grpNumbersLayout")
        self.textEdit_20 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_20.setEnabled(False)
        self.textEdit_20.setReadOnly(True)
        self.textEdit_20.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_20.setObjectName("textEdit_20")
        self.grpNumbersLayout.addWidget(self.textEdit_20, 3, 1, 1, 1)
        self.txtSp_4 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txtSp_4.setEnabled(False)
        self.txtSp_4.setReadOnly(True)
        self.txtSp_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txtSp_4.setObjectName("txtSp_4")
        self.grpNumbersLayout.addWidget(self.txtSp_4, 4, 7, 1, 1)
        self.textEdit_29 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_29.setEnabled(False)
        self.textEdit_29.setReadOnly(True)
        self.textEdit_29.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_29.setObjectName("textEdit_29")
        self.grpNumbersLayout.addWidget(self.textEdit_29, 4, 4, 1, 1)
        self.textEdit_25 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_25.setEnabled(False)
        self.textEdit_25.setReadOnly(True)
        self.textEdit_25.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_25.setObjectName("textEdit_25")
        self.grpNumbersLayout.addWidget(self.textEdit_25, 4, 0, 1, 1)
        self.textEdit_28 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_28.setEnabled(False)
        self.textEdit_28.setReadOnly(True)
        self.textEdit_28.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_28.setObjectName("textEdit_28")
        self.grpNumbersLayout.addWidget(self.textEdit_28, 4, 3, 1, 1)
        self.textEdit_26 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_26.setEnabled(False)
        self.textEdit_26.setReadOnly(True)
        self.textEdit_26.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_26.setObjectName("textEdit_26")
        self.grpNumbersLayout.addWidget(self.textEdit_26, 4, 1, 1, 1)
        self.textEdit_27 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_27.setEnabled(False)
        self.textEdit_27.setReadOnly(True)
        self.textEdit_27.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_27.setObjectName("textEdit_27")
        self.grpNumbersLayout.addWidget(self.textEdit_27, 4, 2, 1, 1)
        self.textEdit_22 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_22.setEnabled(False)
        self.textEdit_22.setReadOnly(True)
        self.textEdit_22.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_22.setObjectName("textEdit_22")
        self.grpNumbersLayout.addWidget(self.textEdit_22, 3, 3, 1, 1)
        self.textEdit_21 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_21.setEnabled(False)
        self.textEdit_21.setReadOnly(True)
        self.textEdit_21.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_21.setObjectName("textEdit_21")
        self.grpNumbersLayout.addWidget(self.textEdit_21, 3, 2, 1, 1)
        self.txtSp_3 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txtSp_3.setEnabled(False)
        self.txtSp_3.setReadOnly(True)
        self.txtSp_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txtSp_3.setObjectName("txtSp_3")
        self.grpNumbersLayout.addWidget(self.txtSp_3, 3, 7, 1, 1)
        self.txt_01 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txt_01.setEnabled(False)
        self.txt_01.setReadOnly(True)
        self.txt_01.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txt_01.setObjectName("txt_01")
        self.grpNumbersLayout.addWidget(self.txt_01, 0, 0, 1, 1)
        self.textEdit_23 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_23.setEnabled(False)
        self.textEdit_23.setReadOnly(True)
        self.textEdit_23.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_23.setObjectName("textEdit_23")
        self.grpNumbersLayout.addWidget(self.textEdit_23, 3, 4, 1, 1)
        self.textEdit_17 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_17.setEnabled(False)
        self.textEdit_17.setReadOnly(True)
        self.textEdit_17.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_17.setObjectName("textEdit_17")
        self.grpNumbersLayout.addWidget(self.textEdit_17, 2, 4, 1, 1)
        self.txtSp_2 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txtSp_2.setEnabled(False)
        self.txtSp_2.setReadOnly(True)
        self.txtSp_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txtSp_2.setObjectName("txtSp_2")
        self.grpNumbersLayout.addWidget(self.txtSp_2, 2, 7, 1, 1)
        self.textEdit_19 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_19.setEnabled(False)
        self.textEdit_19.setReadOnly(True)
        self.textEdit_19.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_19.setObjectName("textEdit_19")
        self.grpNumbersLayout.addWidget(self.textEdit_19, 3, 0, 1, 1)
        self.txt_05 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txt_05.setEnabled(False)
        self.txt_05.setReadOnly(True)
        self.txt_05.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txt_05.setObjectName("txt_05")
        self.grpNumbersLayout.addWidget(self.txt_05, 0, 4, 1, 1)
        self.textEdit_11 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_11.setEnabled(False)
        self.textEdit_11.setReadOnly(True)
        self.textEdit_11.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_11.setObjectName("textEdit_11")
        self.grpNumbersLayout.addWidget(self.textEdit_11, 2, 0, 1, 1)
        self.textEdit_12 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_12.setEnabled(False)
        self.textEdit_12.setReadOnly(True)
        self.textEdit_12.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_12.setObjectName("textEdit_12")
        self.grpNumbersLayout.addWidget(self.textEdit_12, 2, 1, 1, 1)
        self.textEdit_13 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_13.setEnabled(False)
        self.textEdit_13.setReadOnly(True)
        self.textEdit_13.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_13.setObjectName("textEdit_13")
        self.grpNumbersLayout.addWidget(self.textEdit_13, 2, 2, 1, 1)
        self.textEdit_16 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_16.setEnabled(False)
        self.textEdit_16.setReadOnly(True)
        self.textEdit_16.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_16.setObjectName("textEdit_16")
        self.grpNumbersLayout.addWidget(self.textEdit_16, 1, 4, 1, 1)
        self.textEdit_14 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_14.setEnabled(False)
        self.textEdit_14.setReadOnly(True)
        self.textEdit_14.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_14.setObjectName("textEdit_14")
        self.grpNumbersLayout.addWidget(self.textEdit_14, 2, 3, 1, 1)
        self.txt_04 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txt_04.setEnabled(False)
        self.txt_04.setReadOnly(True)
        self.txt_04.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txt_04.setObjectName("txt_04")
        self.grpNumbersLayout.addWidget(self.txt_04, 0, 3, 1, 1)
        self.txt_02 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txt_02.setEnabled(False)
        self.txt_02.setReadOnly(True)
        self.txt_02.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txt_02.setObjectName("txt_02")
        self.grpNumbersLayout.addWidget(self.txt_02, 0, 1, 1, 1)
        self.txt_03 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txt_03.setEnabled(False)
        self.txt_03.setReadOnly(True)
        self.txt_03.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txt_03.setObjectName("txt_03")
        self.grpNumbersLayout.addWidget(self.txt_03, 0, 2, 1, 1)
        self.txt_10 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txt_10.setEnabled(False)
        self.txt_10.setReadOnly(True)
        self.txt_10.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txt_10.setObjectName("txt_10")
        self.grpNumbersLayout.addWidget(self.txt_10, 1, 0, 1, 1)
        self.txt_11 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txt_11.setEnabled(False)
        self.txt_11.setReadOnly(True)
        self.txt_11.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txt_11.setObjectName("txt_11")
        self.grpNumbersLayout.addWidget(self.txt_11, 1, 1, 1, 1)
        self.txtSp_0 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txtSp_0.setEnabled(False)
        self.txtSp_0.setReadOnly(True)
        self.txtSp_0.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txtSp_0.setObjectName("txtSp_0")
        self.grpNumbersLayout.addWidget(self.txtSp_0, 0, 7, 1, 1)
        self.textEdit_8 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_8.setEnabled(False)
        self.textEdit_8.setReadOnly(True)
        self.textEdit_8.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_8.setObjectName("textEdit_8")
        self.grpNumbersLayout.addWidget(self.textEdit_8, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.grpNumbers)
        self.label_2.setMinimumSize(QtCore.QSize(10, 0))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.grpNumbersLayout.addWidget(self.label_2, 0, 6, 1, 1)
        self.textEdit_9 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_9.setEnabled(False)
        self.textEdit_9.setReadOnly(True)
        self.textEdit_9.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_9.setObjectName("textEdit_9")
        self.grpNumbersLayout.addWidget(self.textEdit_9, 1, 3, 1, 1)
        self.txtSp_1 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txtSp_1.setEnabled(False)
        self.txtSp_1.setReadOnly(True)
        self.txtSp_1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txtSp_1.setObjectName("txtSp_1")
        self.grpNumbersLayout.addWidget(self.txtSp_1, 1, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.grpNumbers)
        self.label_3.setMinimumSize(QtCore.QSize(10, 0))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.grpNumbersLayout.addWidget(self.label_3, 1, 6, 1, 1)
        self.txt_06 = QtWidgets.QTextEdit(self.grpNumbers)
        self.txt_06.setEnabled(False)
        self.txt_06.setReadOnly(True)
        self.txt_06.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txt_06.setObjectName("txt_06")
        self.grpNumbersLayout.addWidget(self.txt_06, 0, 5, 1, 1)
        self.textEdit_32 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_32.setEnabled(False)
        self.textEdit_32.setReadOnly(True)
        self.textEdit_32.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_32.setObjectName("textEdit_32")
        self.grpNumbersLayout.addWidget(self.textEdit_32, 1, 5, 1, 1)
        self.textEdit_33 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_33.setEnabled(False)
        self.textEdit_33.setReadOnly(True)
        self.textEdit_33.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_33.setObjectName("textEdit_33")
        self.grpNumbersLayout.addWidget(self.textEdit_33, 2, 5, 1, 1)
        self.textEdit_34 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_34.setEnabled(False)
        self.textEdit_34.setReadOnly(True)
        self.textEdit_34.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_34.setObjectName("textEdit_34")
        self.grpNumbersLayout.addWidget(self.textEdit_34, 3, 5, 1, 1)
        self.textEdit_35 = QtWidgets.QTextEdit(self.grpNumbers)
        self.textEdit_35.setEnabled(False)
        self.textEdit_35.setReadOnly(True)
        self.textEdit_35.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_35.setObjectName("textEdit_35")
        self.grpNumbersLayout.addWidget(self.textEdit_35, 4, 5, 1, 1)
        self.horizontalLayout_2.addWidget(self.grpNumbers)
        self.grpBets = QtWidgets.QGroupBox(self.frame_2)
        self.grpBets.setMaximumSize(QtCore.QSize(16777215, 400))
        self.grpBets.setObjectName("grpBets")
        self.grpBetsLayout = QtWidgets.QVBoxLayout(self.grpBets)
        self.grpBetsLayout.setObjectName("grpBetsLayout")
        self.rdBets_1 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_1.setObjectName("rdBets_1")
        self.grpBetsLayout.addWidget(self.rdBets_1)
        self.rdBets_2 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_2.setObjectName("rdBets_2")
        self.grpBetsLayout.addWidget(self.rdBets_2)
        self.rdBets_3 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_3.setObjectName("rdBets_3")
        self.grpBetsLayout.addWidget(self.rdBets_3)
        self.rdBets_4 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_4.setObjectName("rdBets_4")
        self.grpBetsLayout.addWidget(self.rdBets_4)
        self.rdBets_5 = QtWidgets.QRadioButton(self.grpBets)
        self.rdBets_5.setObjectName("rdBets_5")
        self.grpBetsLayout.addWidget(self.rdBets_5)
        self.horizontalLayout_2.addWidget(self.grpBets)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnStart = QtWidgets.QPushButton(self.frame_3)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_3.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(self.frame_3)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_3.addWidget(self.btnStop)
        self.btnAutoGenerate = QtWidgets.QPushButton(self.frame_3)
        self.btnAutoGenerate.setObjectName("btnAutoGenerate")
        self.horizontalLayout_3.addWidget(self.btnAutoGenerate)
        self.btnReturn = QtWidgets.QPushButton(self.frame_3)
        self.btnReturn.setObjectName("btnReturn")
        self.horizontalLayout_3.addWidget(self.btnReturn)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "传统型体育彩票"))
        self.grpNumbers.setTitle(_translate("Dialog", "幸运号码"))
        self.grpBets.setTitle(_translate("Dialog", "请投注"))
        self.rdBets_1.setText(_translate("Dialog", "第一注"))
        self.rdBets_2.setText(_translate("Dialog", "第二注"))
        self.rdBets_3.setText(_translate("Dialog", "第三注"))
        self.rdBets_4.setText(_translate("Dialog", "第四注"))
        self.rdBets_5.setText(_translate("Dialog", "第五注"))
        self.btnStart.setText(_translate("Dialog", "开始"))
        self.btnStop.setText(_translate("Dialog", "停止"))
        self.btnAutoGenerate.setText(_translate("Dialog", "自动"))
        self.btnReturn.setText(_translate("Dialog", "返回"))

