# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(619, 330)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resource/Icon1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Resource/Canon.jpg"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.displayFrame = DisplayFrame(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.displayFrame.sizePolicy().hasHeightForWidth())
        self.displayFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.displayFrame.setFont(font)
        self.displayFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.displayFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.displayFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.displayFrame.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayFrame.setObjectName("displayFrame")
        self.horizontalLayout_2.addWidget(self.displayFrame)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(-1, 11, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnArctan = QtWidgets.QPushButton(self.widget)
        self.btnArctan.setAutoFillBackground(False)
        self.btnArctan.setObjectName("btnArctan")
        self.gridLayout.addWidget(self.btnArctan, 1, 2, 1, 1)
        self.btnArcsin = QtWidgets.QPushButton(self.widget)
        self.btnArcsin.setAutoFillBackground(False)
        self.btnArcsin.setObjectName("btnArcsin")
        self.gridLayout.addWidget(self.btnArcsin, 1, 0, 1, 1)
        self.btnLn = QtWidgets.QPushButton(self.widget)
        self.btnLn.setAutoFillBackground(False)
        self.btnLn.setObjectName("btnLn")
        self.gridLayout.addWidget(self.btnLn, 1, 5, 1, 1)
        self.btnArccos = QtWidgets.QPushButton(self.widget)
        self.btnArccos.setAutoFillBackground(False)
        self.btnArccos.setObjectName("btnArccos")
        self.gridLayout.addWidget(self.btnArccos, 1, 1, 1, 1)
        self.btnCos = QtWidgets.QPushButton(self.widget)
        self.btnCos.setAutoFillBackground(False)
        self.btnCos.setObjectName("btnCos")
        self.gridLayout.addWidget(self.btnCos, 0, 1, 1, 1)
        self.btnFactorial = QtWidgets.QPushButton(self.widget)
        self.btnFactorial.setAutoFillBackground(False)
        self.btnFactorial.setObjectName("btnFactorial")
        self.gridLayout.addWidget(self.btnFactorial, 0, 5, 1, 1)
        self.btnSec = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSec.sizePolicy().hasHeightForWidth())
        self.btnSec.setSizePolicy(sizePolicy)
        self.btnSec.setAutoFillBackground(False)
        self.btnSec.setObjectName("btnSec")
        self.gridLayout.addWidget(self.btnSec, 0, 4, 1, 1)
        self.btnLog = QtWidgets.QPushButton(self.widget)
        self.btnLog.setAutoFillBackground(False)
        self.btnLog.setObjectName("btnLog")
        self.gridLayout.addWidget(self.btnLog, 1, 4, 1, 1)
        self.btnSin = QtWidgets.QPushButton(self.widget)
        self.btnSin.setAutoFillBackground(False)
        self.btnSin.setObjectName("btnSin")
        self.gridLayout.addWidget(self.btnSin, 0, 0, 1, 1)
        self.btnArcctg = QtWidgets.QPushButton(self.widget)
        self.btnArcctg.setAutoFillBackground(False)
        self.btnArcctg.setObjectName("btnArcctg")
        self.gridLayout.addWidget(self.btnArcctg, 1, 3, 1, 1)
        self.btnTan = QtWidgets.QPushButton(self.widget)
        self.btnTan.setAutoFillBackground(False)
        self.btnTan.setObjectName("btnTan")
        self.gridLayout.addWidget(self.btnTan, 0, 2, 1, 1)
        self.btnCtg = QtWidgets.QPushButton(self.widget)
        self.btnCtg.setAutoFillBackground(False)
        self.btnCtg.setObjectName("btnCtg")
        self.gridLayout.addWidget(self.btnCtg, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(-1, 5, -1, 11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn3 = QtWidgets.QPushButton(self.widget_2)
        self.btn3.setAutoFillBackground(False)
        self.btn3.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn3.setObjectName("btn3")
        self.gridLayout_2.addWidget(self.btn3, 2, 3, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.widget_2)
        self.btn6.setAutoFillBackground(False)
        self.btn6.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn6.setObjectName("btn6")
        self.gridLayout_2.addWidget(self.btn6, 1, 3, 1, 1)
        self.btnClear = QtWidgets.QPushButton(self.widget_2)
        self.btnClear.setAutoFillBackground(False)
        self.btnClear.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnClear.setObjectName("btnClear")
        self.gridLayout_2.addWidget(self.btnClear, 0, 5, 1, 1)
        self.btnAdd = QtWidgets.QPushButton(self.widget_2)
        self.btnAdd.setAutoFillBackground(False)
        self.btnAdd.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout_2.addWidget(self.btnAdd, 2, 4, 1, 1)
        self.btnMemoryAdd = QtWidgets.QPushButton(self.widget_2)
        self.btnMemoryAdd.setAutoFillBackground(False)
        self.btnMemoryAdd.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnMemoryAdd.setObjectName("btnMemoryAdd")
        self.gridLayout_2.addWidget(self.btnMemoryAdd, 2, 6, 1, 1)
        self.btnClearMemory = QtWidgets.QPushButton(self.widget_2)
        self.btnClearMemory.setAutoFillBackground(False)
        self.btnClearMemory.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnClearMemory.setObjectName("btnClearMemory")
        self.gridLayout_2.addWidget(self.btnClearMemory, 0, 6, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.widget_2)
        self.btn1.setAutoFillBackground(False)
        self.btn1.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn1.setObjectName("btn1")
        self.gridLayout_2.addWidget(self.btn1, 2, 1, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.widget_2)
        self.btn4.setAutoFillBackground(False)
        self.btn4.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn4.setObjectName("btn4")
        self.gridLayout_2.addWidget(self.btn4, 1, 1, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.widget_2)
        self.btn9.setAutoFillBackground(False)
        self.btn9.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn9.setObjectName("btn9")
        self.gridLayout_2.addWidget(self.btn9, 0, 3, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.widget_2)
        self.btn5.setAutoFillBackground(False)
        self.btn5.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn5.setObjectName("btn5")
        self.gridLayout_2.addWidget(self.btn5, 1, 2, 1, 1)
        self.btnCE = QtWidgets.QPushButton(self.widget_2)
        self.btnCE.setAutoFillBackground(False)
        self.btnCE.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnCE.setObjectName("btnCE")
        self.gridLayout_2.addWidget(self.btnCE, 1, 5, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.widget_2)
        self.btn2.setAutoFillBackground(False)
        self.btn2.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn2.setObjectName("btn2")
        self.gridLayout_2.addWidget(self.btn2, 2, 2, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.widget_2)
        self.btn8.setAutoFillBackground(False)
        self.btn8.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn8.setObjectName("btn8")
        self.gridLayout_2.addWidget(self.btn8, 0, 2, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.widget_2)
        self.btn7.setAutoFillBackground(False)
        self.btn7.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn7.setObjectName("btn7")
        self.gridLayout_2.addWidget(self.btn7, 0, 1, 1, 1)
        self.btnReadMemory = QtWidgets.QPushButton(self.widget_2)
        self.btnReadMemory.setAutoFillBackground(False)
        self.btnReadMemory.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnReadMemory.setObjectName("btnReadMemory")
        self.gridLayout_2.addWidget(self.btnReadMemory, 1, 6, 1, 1)
        self.btnDivide = QtWidgets.QPushButton(self.widget_2)
        self.btnDivide.setAutoFillBackground(False)
        self.btnDivide.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnDivide.setObjectName("btnDivide")
        self.gridLayout_2.addWidget(self.btnDivide, 0, 4, 1, 1)
        self.btnMultiply = QtWidgets.QPushButton(self.widget_2)
        self.btnMultiply.setAutoFillBackground(False)
        self.btnMultiply.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnMultiply.setObjectName("btnMultiply")
        self.gridLayout_2.addWidget(self.btnMultiply, 1, 4, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.widget_2)
        self.btn0.setAutoFillBackground(False)
        self.btn0.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.btn0.setObjectName("btn0")
        self.gridLayout_2.addWidget(self.btn0, 3, 1, 1, 1)
        self.btnSign = QtWidgets.QPushButton(self.widget_2)
        self.btnSign.setAutoFillBackground(False)
        self.btnSign.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnSign.setObjectName("btnSign")
        self.gridLayout_2.addWidget(self.btnSign, 3, 2, 1, 1)
        self.btnPeriod = QtWidgets.QPushButton(self.widget_2)
        self.btnPeriod.setAutoFillBackground(False)
        self.btnPeriod.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnPeriod.setObjectName("btnPeriod")
        self.gridLayout_2.addWidget(self.btnPeriod, 3, 3, 1, 1)
        self.btnMinus = QtWidgets.QPushButton(self.widget_2)
        self.btnMinus.setAutoFillBackground(False)
        self.btnMinus.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnMinus.setObjectName("btnMinus")
        self.gridLayout_2.addWidget(self.btnMinus, 3, 4, 1, 1)
        self.btnResult = QtWidgets.QPushButton(self.widget_2)
        self.btnResult.setAutoFillBackground(False)
        self.btnResult.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnResult.setObjectName("btnResult")
        self.gridLayout_2.addWidget(self.btnResult, 3, 5, 1, 1)
        self.btnConversion = QtWidgets.QPushButton(self.widget_2)
        self.btnConversion.setAutoFillBackground(False)
        self.btnConversion.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnConversion.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resource/ARW.ICO"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConversion.setIcon(icon1)
        self.btnConversion.setObjectName("btnConversion")
        self.gridLayout_2.addWidget(self.btnConversion, 3, 6, 1, 1)
        self.btnBackspace = QtWidgets.QPushButton(self.widget_2)
        self.btnBackspace.setAutoFillBackground(False)
        self.btnBackspace.setStyleSheet("background-color: rgb(255,255,255);")
        self.btnBackspace.setObjectName("btnBackspace")
        self.gridLayout_2.addWidget(self.btnBackspace, 2, 5, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "计算器"))
        self.displayFrame.setText(_translate("Form", "0"))
        self.btnArctan.setText(_translate("Form", "arctan"))
        self.btnArcsin.setText(_translate("Form", "arcsin"))
        self.btnLn.setText(_translate("Form", "ln"))
        self.btnArccos.setText(_translate("Form", "arccos"))
        self.btnCos.setText(_translate("Form", "cos"))
        self.btnFactorial.setText(_translate("Form", "n!"))
        self.btnSec.setText(_translate("Form", "sec"))
        self.btnLog.setText(_translate("Form", "log"))
        self.btnSin.setText(_translate("Form", "sin"))
        self.btnArcctg.setText(_translate("Form", "arcctn"))
        self.btnTan.setText(_translate("Form", "tan"))
        self.btnCtg.setText(_translate("Form", "ctg"))
        self.btn3.setText(_translate("Form", "3"))
        self.btn3.setShortcut(_translate("Form", "3"))
        self.btn6.setText(_translate("Form", "6"))
        self.btn6.setShortcut(_translate("Form", "6"))
        self.btnClear.setText(_translate("Form", "C"))
        self.btnAdd.setText(_translate("Form", "+"))
        self.btnAdd.setShortcut(_translate("Form", "+"))
        self.btnMemoryAdd.setText(_translate("Form", "M+"))
        self.btnClearMemory.setText(_translate("Form", "0→M"))
        self.btn1.setText(_translate("Form", "1"))
        self.btn1.setShortcut(_translate("Form", "1"))
        self.btn4.setText(_translate("Form", "4"))
        self.btn4.setShortcut(_translate("Form", "4"))
        self.btn9.setText(_translate("Form", "9"))
        self.btn9.setShortcut(_translate("Form", "9"))
        self.btn5.setText(_translate("Form", "5"))
        self.btn5.setShortcut(_translate("Form", "5"))
        self.btnCE.setText(_translate("Form", "CE"))
        self.btn2.setText(_translate("Form", "2"))
        self.btn2.setShortcut(_translate("Form", "2"))
        self.btn8.setText(_translate("Form", "8"))
        self.btn8.setShortcut(_translate("Form", "8"))
        self.btn7.setText(_translate("Form", "7"))
        self.btn7.setShortcut(_translate("Form", "7"))
        self.btnReadMemory.setText(_translate("Form", "RM"))
        self.btnDivide.setText(_translate("Form", "÷"))
        self.btnDivide.setShortcut(_translate("Form", "/"))
        self.btnMultiply.setText(_translate("Form", "×"))
        self.btnMultiply.setShortcut(_translate("Form", "*"))
        self.btn0.setText(_translate("Form", "0"))
        self.btn0.setShortcut(_translate("Form", "0"))
        self.btnSign.setText(_translate("Form", "+/-"))
        self.btnPeriod.setText(_translate("Form", "."))
        self.btnPeriod.setShortcut(_translate("Form", "."))
        self.btnMinus.setText(_translate("Form", "-"))
        self.btnMinus.setShortcut(_translate("Form", "-"))
        self.btnResult.setText(_translate("Form", "="))
        self.btnResult.setShortcut(_translate("Form", "Return"))
        self.btnBackspace.setText(_translate("Form", "→"))
        self.btnBackspace.setShortcut(_translate("Form", "Backspace"))
from display_frame import DisplayFrame
