# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panel.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(863, 464)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rdBigFont = QtWidgets.QRadioButton(self.groupBox)
        self.rdBigFont.setChecked(True)
        self.rdBigFont.setObjectName("rdBigFont")
        self.horizontalLayout_2.addWidget(self.rdBigFont)
        self.rdSmallFont = QtWidgets.QRadioButton(self.groupBox)
        self.rdSmallFont.setObjectName("rdSmallFont")
        self.horizontalLayout_2.addWidget(self.rdSmallFont)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnStart = QtWidgets.QPushButton(self.frame_2)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.btnRestoreSettings = QtWidgets.QPushButton(self.frame_2)
        self.btnRestoreSettings.setObjectName("btnRestoreSettings")
        self.horizontalLayout.addWidget(self.btnRestoreSettings)
        self.btnHide = QtWidgets.QPushButton(self.frame_2)
        self.btnHide.setObjectName("btnHide")
        self.horizontalLayout.addWidget(self.btnHide)
        self.btnExit = QtWidgets.QPushButton(self.frame_2)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout.addWidget(self.btnExit)
        self.gridLayout.addWidget(self.frame_2, 4, 0, 1, 2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.cbForeground = QtWidgets.QComboBox(self.frame)
        self.cbForeground.setObjectName("cbForeground")
        self.gridLayout_4.addWidget(self.cbForeground, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.cbBackground = QtWidgets.QComboBox(self.frame)
        self.cbBackground.setObjectName("cbBackground")
        self.gridLayout_4.addWidget(self.cbBackground, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.sldSpeed = QtWidgets.QSlider(self.frame)
        self.sldSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.sldSpeed.setObjectName("sldSpeed")
        self.gridLayout_4.addWidget(self.sldSpeed, 0, 3, 1, 1)
        self.cbChangeColor = QtWidgets.QCheckBox(self.frame)
        self.cbChangeColor.setObjectName("cbChangeColor")
        self.gridLayout_4.addWidget(self.cbChangeColor, 1, 2, 1, 2)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 2)
        self.txtCustom = QtWidgets.QLineEdit(Dialog)
        self.txtCustom.setObjectName("txtCustom")
        self.gridLayout.addWidget(self.txtCustom, 3, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.font_name_layout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.font_name_layout.setObjectName("font_name_layout")
        self.btnSongTi = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSongTi.setCheckable(True)
        self.btnSongTi.setChecked(True)
        self.btnSongTi.setAutoExclusive(True)
        self.btnSongTi.setObjectName("btnSongTi")
        self.font_name_layout.addWidget(self.btnSongTi)
        self.btnLiShu = QtWidgets.QPushButton(self.groupBox_2)
        self.btnLiShu.setCheckable(True)
        self.btnLiShu.setAutoExclusive(True)
        self.btnLiShu.setObjectName("btnLiShu")
        self.font_name_layout.addWidget(self.btnLiShu)
        self.btnKaiTi = QtWidgets.QPushButton(self.groupBox_2)
        self.btnKaiTi.setCheckable(True)
        self.btnKaiTi.setAutoExclusive(True)
        self.btnKaiTi.setObjectName("btnKaiTi")
        self.font_name_layout.addWidget(self.btnKaiTi)
        self.btnHeiTi = QtWidgets.QPushButton(self.groupBox_2)
        self.btnHeiTi.setCheckable(True)
        self.btnHeiTi.setAutoExclusive(True)
        self.btnHeiTi.setObjectName("btnHeiTi")
        self.font_name_layout.addWidget(self.btnHeiTi)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.direction_layout = QtWidgets.QGridLayout(self.groupBox_4)
        self.direction_layout.setObjectName("direction_layout")
        self.rdOrientRight = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdOrientRight.setObjectName("rdOrientRight")
        self.direction_layout.addWidget(self.rdOrientRight, 0, 0, 1, 1)
        self.rdOrientLeft = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdOrientLeft.setChecked(True)
        self.rdOrientLeft.setObjectName("rdOrientLeft")
        self.direction_layout.addWidget(self.rdOrientLeft, 0, 1, 1, 1)
        self.rdSwing = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdSwing.setObjectName("rdSwing")
        self.direction_layout.addWidget(self.rdSwing, 1, 0, 1, 1)
        self.rdSwingReflection = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdSwingReflection.setObjectName("rdSwingReflection")
        self.direction_layout.addWidget(self.rdSwingReflection, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.txt_btn_layout = QtWidgets.QGridLayout(self.groupBox_3)
        self.txt_btn_layout.setObjectName("txt_btn_layout")
        self.btnTxt3 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnTxt3.setCheckable(True)
        self.btnTxt3.setAutoExclusive(True)
        self.btnTxt3.setObjectName("btnTxt3")
        self.txt_btn_layout.addWidget(self.btnTxt3, 0, 2, 1, 1)
        self.btnTxt2 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnTxt2.setCheckable(True)
        self.btnTxt2.setAutoExclusive(True)
        self.btnTxt2.setObjectName("btnTxt2")
        self.txt_btn_layout.addWidget(self.btnTxt2, 0, 1, 1, 1)
        self.btnText1 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnText1.setCheckable(True)
        self.btnText1.setChecked(True)
        self.btnText1.setAutoExclusive(True)
        self.btnText1.setObjectName("btnText1")
        self.txt_btn_layout.addWidget(self.btnText1, 0, 0, 1, 1)
        self.btnTxt4 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnTxt4.setCheckable(True)
        self.btnTxt4.setAutoExclusive(True)
        self.btnTxt4.setObjectName("btnTxt4")
        self.txt_btn_layout.addWidget(self.btnTxt4, 0, 3, 1, 1)
        self.btnTxt5 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnTxt5.setCheckable(True)
        self.btnTxt5.setAutoExclusive(True)
        self.btnTxt5.setObjectName("btnTxt5")
        self.txt_btn_layout.addWidget(self.btnTxt5, 1, 0, 1, 1)
        self.btnTxt6 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnTxt6.setCheckable(True)
        self.btnTxt6.setAutoExclusive(True)
        self.btnTxt6.setObjectName("btnTxt6")
        self.txt_btn_layout.addWidget(self.btnTxt6, 1, 1, 1, 1)
        self.btnTxt7 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnTxt7.setCheckable(True)
        self.btnTxt7.setAutoExclusive(True)
        self.btnTxt7.setObjectName("btnTxt7")
        self.txt_btn_layout.addWidget(self.btnTxt7, 1, 2, 1, 1)
        self.btnTxt8 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnTxt8.setCheckable(True)
        self.btnTxt8.setAutoExclusive(True)
        self.btnTxt8.setObjectName("btnTxt8")
        self.txt_btn_layout.addWidget(self.btnTxt8, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "控制板"))
        self.groupBox.setTitle(_translate("Dialog", "滚动字幕的文字大小控制"))
        self.rdBigFont.setText(_translate("Dialog", "大字体"))
        self.rdSmallFont.setText(_translate("Dialog", "小字体"))
        self.btnStart.setText(_translate("Dialog", "开始滚动"))
        self.btnRestoreSettings.setText(_translate("Dialog", "恢复设置"))
        self.btnHide.setText(_translate("Dialog", "隐藏控制板"))
        self.btnExit.setText(_translate("Dialog", "退出"))
        self.label.setText(_translate("Dialog", "背景色："))
        self.label_2.setText(_translate("Dialog", "前景色"))
        self.label_3.setText(_translate("Dialog", "滚动速度："))
        self.cbChangeColor.setText(_translate("Dialog", "颜色自动变化"))
        self.txtCustom.setText(_translate("Dialog", "请在此输入字幕内容并回车"))
        self.groupBox_2.setTitle(_translate("Dialog", "滚动字幕字体控制"))
        self.btnSongTi.setText(_translate("Dialog", "宋体"))
        self.btnLiShu.setText(_translate("Dialog", "隶书"))
        self.btnKaiTi.setText(_translate("Dialog", "楷体"))
        self.btnHeiTi.setText(_translate("Dialog", "黑体"))
        self.groupBox_4.setTitle(_translate("Dialog", "字幕滚动方向控制"))
        self.rdOrientRight.setText(_translate("Dialog", "从左往右"))
        self.rdOrientLeft.setText(_translate("Dialog", "从右往左"))
        self.rdSwing.setText(_translate("Dialog", "穿透式左右摆动"))
        self.rdSwingReflection.setText(_translate("Dialog", "镜面反射式摆动"))
        self.groupBox_3.setTitle(_translate("Dialog", "内置字幕"))
        self.btnTxt3.setText(_translate("Dialog", "3"))
        self.btnTxt2.setText(_translate("Dialog", "2"))
        self.btnText1.setText(_translate("Dialog", "1"))
        self.btnTxt4.setText(_translate("Dialog", "4"))
        self.btnTxt5.setText(_translate("Dialog", "5"))
        self.btnTxt6.setText(_translate("Dialog", "6"))
        self.btnTxt7.setText(_translate("Dialog", "7"))
        self.btnTxt8.setText(_translate("Dialog", "8"))

