# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 497)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbNone = QtWidgets.QRadioButton(self.frame)
        self.rbNone.setObjectName("rbNone")
        self.gridLayout_2.addWidget(self.rbNone, 0, 0, 1, 1)
        self.rbTwo = QtWidgets.QRadioButton(self.frame)
        self.rbTwo.setObjectName("rbTwo")
        self.gridLayout_2.addWidget(self.rbTwo, 1, 0, 1, 1)
        self.rbOne = QtWidgets.QRadioButton(self.frame)
        self.rbOne.setObjectName("rbOne")
        self.gridLayout_2.addWidget(self.rbOne, 0, 1, 1, 1)
        self.rbThree = QtWidgets.QRadioButton(self.frame)
        self.rbThree.setObjectName("rbThree")
        self.gridLayout_2.addWidget(self.rbThree, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateStart = QtWidgets.QDateEdit(self.frame_2)
        self.dateStart.setCalendarPopup(False)
        self.dateStart.setObjectName("dateStart")
        self.horizontalLayout.addWidget(self.dateStart)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 3)
        self.btnEqualTotal = QtWidgets.QPushButton(Dialog)
        self.btnEqualTotal.setObjectName("btnEqualTotal")
        self.gridLayout.addWidget(self.btnEqualTotal, 4, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 2)
        self.btnEqualPrincipal = QtWidgets.QPushButton(Dialog)
        self.btnEqualPrincipal.setObjectName("btnEqualPrincipal")
        self.gridLayout.addWidget(self.btnEqualPrincipal, 5, 0, 1, 3)
        self.btnExit = QtWidgets.QPushButton(Dialog)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 6, 0, 1, 3)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.cbYears = QtWidgets.QComboBox(Dialog)
        self.cbYears.setObjectName("cbYears")
        self.gridLayout.addWidget(self.cbYears, 1, 1, 1, 2)
        self.txtAmount = QtWidgets.QLineEdit(Dialog)
        self.txtAmount.setObjectName("txtAmount")
        self.gridLayout.addWidget(self.txtAmount, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialog", "享受政策性贷款人数"))
        self.rbNone.setText(_translate("Dialog", "无人"))
        self.rbTwo.setText(_translate("Dialog", "二人"))
        self.rbOne.setText(_translate("Dialog", "一人"))
        self.rbThree.setText(_translate("Dialog", "三人"))
        self.label_3.setText(_translate("Dialog", "(万元）"))
        self.groupBox.setTitle(_translate("Dialog", "还款起始年月"))
        self.dateStart.setDisplayFormat(_translate("Dialog", "yyyy/M"))
        self.btnEqualTotal.setText(_translate("Dialog", "等额本息还款法"))
        self.btnEqualPrincipal.setText(_translate("Dialog", "等额本金还款法"))
        self.btnExit.setText(_translate("Dialog", "退出"))
        self.label.setText(_translate("Dialog", "贷款总额"))
        self.label_2.setText(_translate("Dialog", "还款年数"))

